### ISSUE TITLE
All drones are in random motion

### ISSUE THREAD

**Issue by Lyn6969** [csviragh/robotsim#1]
I used "make spp_evol" to compile all files and ran the robotsim_main.c without any problem.But all drones are in random motion.There was no flocking behavior as the video "Flocking simulation of 100 drones at 4m/s with algo from 2017" shows.What is the reason for this?Why can't I achieve same results as yours ?

**Comment by vasarhelyi** [comment]
As discussed in email, it was due to the fact that the range of alignment was set too low (below the range of repulsion).

**Comment by liyanan24** [comment]
> As discussed in email, it was due to the fact that the range of alignment was set too low (below the range of repulsion).



> As discussed in email, it was due to the fact that the range of alignment was set too low (below the range of repulsion).

**Comment by Lyn6969** [comment]
> As discussed in email, it was due to the fact that the range of alignment was set too low (below the range of repulsion).

Thanks!
